[project]
id = "mpbrjezmxmrdhgtvldvi"

[functions.generate-insights]
verify_jwt = false

[functions.process-file]
verify_jwt = false

[functions.create-workspace-schema]
verify_jwt = false

[functions.insert-workspace-data]
verify_jwt = false

[functions.query-workspace-data]
verify_jwt = false

[functions.list-workspace-datasets]
verify_jwt = false

[functions.data-chat]
verify_jwt = false
